apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus.yaml
- grafana.yaml
- loki.yaml
- alertmanager.yaml

namespace: devops-monitoring

commonLabels:
  app.kubernetes.io/part-of: devops-lab
  app.kubernetes.io/component: monitoring
