apiVersion: v1
kind: Namespace
metadata:
  name: devops-authelia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data
  namespace: devops-authelia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: devops-authelia
data:
  configuration.yml: |
    server:
      address: 'tcp4://:9091'
    
    log:
      level: debug
      keep_stdout: true
    
    identity_validation:
      elevated_session:
        require_second_factor: true
      reset_password:
        jwt_lifespan: '5 minutes'
        jwt_secret: 'devops-lab-jwt-secret-key-for-testing-only'
    
    totp:
      disable: false
      issuer: 'devops.localhost'
      period: 30
      skew: 1
    
    password_policy:
      zxcvbn:
        enabled: true
        min_score: 4
    
    authentication_backend:
      file:
        path: '/config/users.yml'
        password:
          algorithm: 'argon2'
          argon2:
            variant: 'argon2id'
            iterations: 3
            memory: 65535
            parallelism: 4
            key_length: 32
            salt_length: 16
    
    access_control:
      default_policy: 'deny'
      rules:
        - domain: 'devops.localhost'
          policy: 'bypass'
        - domain: '*.devops.localhost'
          policy: 'bypass'
    
    session:
      name: 'authelia_session'
      secret: 'devops-lab-session-secret-key-for-testing-only'
      cookies:
        - domain: 'devops.localhost'
          authelia_url: 'https://auth.devops.localhost'
    
    regulation:
      max_retries: 4
      find_time: 120
      ban_time: 300
    
    storage:
      encryption_key: 'devops-lab-storage-encryption-key-for-testing-only'
      local:
        path: '/config/db.sqlite3'
    
    notifier:
      disable_startup_check: false
      filesystem:
        filename: '/config/notification.txt'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: devops-authelia
data:
  users.yml: |
    users:
      admin:
        displayname: 'Admin User'
        password: '$6$rounds=50000$BpLnfgDsc2WD8F2q$Zis.ixdg9s/UOJYrs56b5QEZFiZECu0qZVNsIYxBaNJ7ucIL.nlxVCT5tqh8KHG8X4tlwCFm5r6NTOZZ5qRFN/'
        email: 'admin@devops.localhost'
        groups:
          - 'admin'
          - 'dev'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: devops-authelia
  labels:
    app: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - name: authelia
        image: authelia/authelia:4.38
        ports:
        - containerPort: 9091
          name: http
        env:
        - name: AUTHELIA_CONFIG_FILE
          value: "/config/configuration.yml"
        volumeMounts:
        - name: authelia-data
          mountPath: /config
        - name: authelia-config
          mountPath: /config/configuration.yml
          subPath: configuration.yml
        - name: authelia-users
          mountPath: /config/users.yml
          subPath: users.yml
      volumes:
      - name: authelia-data
        persistentVolumeClaim:
          claimName: authelia-data
      - name: authelia-config
        configMap:
          name: authelia-config
      - name: authelia-users
        configMap:
          name: authelia-users
---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: devops-authelia
  labels:
    app: authelia
spec:
  selector:
    app: authelia
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9091
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia-ingress
  namespace: devops-authelia
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: auth.devops.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authelia
            port:
              number: 8080
