apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sonarqube.yaml

namespace: devops-sonarqube

commonLabels:
  app.kubernetes.io/part-of: devops-lab
  app.kubernetes.io/component: sonarqube
