expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.devops.localhost
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "standard"
      size: 5Gi
    database:
      storageClass: "standard"
      size: 1Gi
    redis:
      storageClass: "standard"
      size: 1Gi

harborAdminPassword: "Harbor12345"

database:
  type: internal
  internal:
    password: "root123"

redis:
  type: internal

registry:
  storage:
    type: filesystem
    filesystem:
      rootdirectory: /storage
