apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- vault.yaml

namespace: devops-vault

commonLabels:
  app.kubernetes.io/part-of: devops-lab
  app.kubernetes.io/component: vault
