apiVersion: v1
kind: Namespace
metadata:
  name: devops-gitea
  labels:
    name: devops-gitea

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: devops-gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: devops-gitea
data:
  app.ini: |
    [database]
    DB_TYPE = sqlite3
    DB_PATH = /data/gitea/gitea.db
    
    [server]
    DOMAIN = localhost
    HTTP_PORT = 3000
    ROOT_URL = http://localhost:3000/
    DISABLE_SSH = true
    
    [service]
    DISABLE_REGISTRATION = false
    REQUIRE_SIGNIN_VIEW = false
    
    [security]
    INSTALL_LOCK = true
    SECRET_KEY = $(openssl rand -base64 32)
    
    [log]
    LEVEL = Info
    ROOT_PATH = /data/gitea/log

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: devops-gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.21
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GITEA__database__DB_TYPE
          value: "sqlite3"
        - name: GITEA__database__PATH
          value: "/data/gitea/gitea.db"
        - name: GITEA__server__DOMAIN
          value: "localhost"
        - name: GITEA__server__HTTP_PORT
          value: "3000"
        - name: GITEA__server__ROOT_URL
          value: "http://localhost:4000/"
        - name: GITEA__server__DISABLE_SSH
          value: "true"
        - name: GITEA__service__DISABLE_REGISTRATION
          value: "false"
        - name: GITEA__security__INSTALL_LOCK
          value: "true"
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        volumeMounts:
        - name: gitea-data
          mountPath: /data
        - name: gitea-config
          mountPath: /etc/gitea
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-data
      - name: gitea-config
        configMap:
          name: gitea-config

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: devops-gitea
  labels:
    app: gitea
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: gitea

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-ingress
  namespace: devops-gitea
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gitea.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea-http
            port:
              number: 3000
